import requests
from telebot import types
from bs4 import BeautifulSoup

# def parser(url):
#     response = requests.get(url)
#
#     # Парсинг HTML страницы
#     soup = BeautifulSoup(response.content, "html.parser")
#
#     # Извлечение данных о продуктах и ценах
#     products = []
#     for product in soup.find_all("a", class_="product-layout product-list col-xs-12"):
#         name = product.find("span").text
#         # price = product.find("div", class_="price").text.split('\n')[1]
#         products.append(name)
#     return products


menu = types.ReplyKeyboardMarkup(resize_keyboard=True)
btn1 = types.KeyboardButton('Купить')
btn2 = types.KeyboardButton('Аккаунт')
btn3 = types.KeyboardButton('Реф. система')
btn4 = types.KeyboardButton('О нас')
menu.row(btn1)
menu.row(btn2, btn3)
menu.row(btn4)

agree = types.ReplyKeyboardMarkup(resize_keyboard=True)
btn1 = types.KeyboardButton('✔ Подтвердить')
btn2 = types.KeyboardButton('❌ Отмена')
agree.row(btn1, btn2)

category = types.ReplyKeyboardMarkup(resize_keyboard=True)
btn1 = types.KeyboardButton('СТЕКЛА, ЧЕХЛЫ')
btn2 = types.KeyboardButton('УМНЫЕ и СТИЛЬНЫЕ SMART-ЧАСЫ')
btn3 = types.KeyboardButton('КАБЕЛИ, З/У, УДЛИНИТЕЛИ')
btn4 = types.KeyboardButton('НОСИТЕЛИ ИНФОРМАЦИИ')
btn5 = types.KeyboardButton('ЭЛЕМЕНТЫ ПИТАНИЯ')
btn6 = types.KeyboardButton('АКУСТИЧЕСКИЕ СИСТЕМЫ')
btn7 = types.KeyboardButton('КОМПЬЮТЕРНЫЕ АКСЕССУАРЫ')
btn8 = types.KeyboardButton('МОБИЛЬНЫЕ АКСЕCСУАРЫ И ИНСТРУМЕНТЫ')
btn9 = types.KeyboardButton('Продукция Xiaomi')
btn10 = types.KeyboardButton('ЭЛЕКТРОНИКА')
btn11 = types.KeyboardButton('АВТОАКСЕССУАРЫ')
btn12 = types.KeyboardButton('ФОНАРИ, НОЖИ, РАЦИИ, ТУРИЗМ')
btn13 = types.KeyboardButton('⬅ Назад')
category.row(btn1, btn2)
category.row(btn3, btn4)
category.row(btn5, btn6)
category.row(btn7, btn8)
category.row(btn9, btn10)
category.row(btn11, btn12)
category.row(btn13)

subcategory_1_0 = types.ReplyKeyboardMarkup(resize_keyboard=True)
btn1 = types.KeyboardButton('ЧЕХЛЫ')
btn2 = types.KeyboardButton('ЗАЩИТНЫЕ СТЁКЛА')
btn3 = types.KeyboardButton('Кардхолдеры')
btn4 = types.KeyboardButton('Ремешки, браслеты')
btn5 = types.KeyboardButton('Чехлы для APods')
btn6 = types.KeyboardButton('Стилусы,прочее')
btn13 = types.KeyboardButton('⬅ Назад')
subcategory_1_0.row(btn1, btn2)
subcategory_1_0.row(btn3, btn4)
subcategory_1_0.row(btn5, btn6)
subcategory_1_0.row(btn13)

subcategory_1_1 = types.ReplyKeyboardMarkup(resize_keyboard=True)
btn1 = types.KeyboardButton('Чехлы для iP')
btn2 = types.KeyboardButton('Чехлы для Samsung')
btn3 = types.KeyboardButton('Чехлы для XiaoMi')
btn4 = types.KeyboardButton('Чехлы для Huawei')
btn5 = types.KeyboardButton('Чехлы для Realme')
btn6 = types.KeyboardButton('Чехлы для Tecno')
btn7 = types.KeyboardButton('Чехлы универсальные')
btn13 = types.KeyboardButton('⬅ Назад')
subcategory_1_1.row(btn1, btn2)
subcategory_1_1.row(btn3, btn4)
subcategory_1_1.row(btn5, btn6)
subcategory_1_1.row(btn7)
subcategory_1_1.row(btn13)

subcategory_1_1_1 = types.ReplyKeyboardMarkup(resize_keyboard=True)
btn1 = types.KeyboardButton('Чехлы для iP 11')
btn2 = types.KeyboardButton('Чехлы для iP 14 Pro Max')
btn3 = types.KeyboardButton('Чехлы для iP 14 Max')
btn4 = types.KeyboardButton('Чехлы для iP 14 Pro')
btn5 = types.KeyboardButton('Чехлы для iP 14')
btn6 = types.KeyboardButton('Чехлы для iP 13 Pro Max')
btn7 = types.KeyboardButton('Чехлы для iP 13 Pro')
btn8 = types.KeyboardButton('Чехлы для iP 13')
btn9 = types.KeyboardButton('Чехлы для iP 13 Mini')
btn10 = types.KeyboardButton('Чехлы для iP 12 Pro Max')
btn11 = types.KeyboardButton('Чехлы для iP 12/12Pro')
btn12 = types.KeyboardButton('Чехлы для iP 12 Mini')
btn13 = types.KeyboardButton('Чехлы для iP 11 Pro Max')
btn14 = types.KeyboardButton('Чехлы для iP 11 Pro')
btn15 = types.KeyboardButton('Чехлы для iP XR')
btn16 = types.KeyboardButton('Чехлы для iP X/XS')
btn17 = types.KeyboardButton('Чехлы для iP XS MAX')
btn18 = types.KeyboardButton('Чехлы для iP 7/8 Plus')
btn19 = types.KeyboardButton('Чехлы для iP 7/8/SE')
btn20 = types.KeyboardButton('Чехлы для iP 6,6 Plus')
btn21 = types.KeyboardButton('Чехлы для iP 5/SE')
btn22 = types.KeyboardButton('⬅ Назад')
subcategory_1_1_1.row(btn1, btn2)
subcategory_1_1_1.row(btn3, btn4)
subcategory_1_1_1.row(btn5, btn6)
subcategory_1_1_1.row(btn7, btn8)
subcategory_1_1_1.row(btn9, btn10)
subcategory_1_1_1.row(btn11, btn12)
subcategory_1_1_1.row(btn13, btn14)
subcategory_1_1_1.row(btn15, btn16)
subcategory_1_1_1.row(btn17, btn18)
subcategory_1_1_1.row(btn19, btn20)
subcategory_1_1_1.row(btn21)
subcategory_1_1_1.row(btn22)

subcategory_2 = types.ReplyKeyboardMarkup(resize_keyboard=True)
btn1 = types.KeyboardButton('Smart Watch (фитнес браслеты) HOCO, BOROFONE, AWEI, XiaoMi')
btn2 = types.KeyboardButton('Smart Watch (фитнес браслеты) ОРБИТА, КОПИИ')
btn3 = types.KeyboardButton('Аксессуары для Smart Watch (фитнес браслетов)')
btn13 = types.KeyboardButton('⬅ Назад')
subcategory_2.row(btn1, btn2)
subcategory_2.row(btn3)
subcategory_2.row(btn13)

page = types.ReplyKeyboardMarkup(resize_keyboard=True)
btn1 = types.KeyboardButton('Следующая страница➡')
btn22 = types.KeyboardButton('⬅ Назад')
page.row(btn1)
page.row(btn22)

page_1 = types.ReplyKeyboardMarkup(resize_keyboard=True)
btn1 = types.KeyboardButton('⬅Предыдущая страница')
btn2 = types.KeyboardButton('Следующая страница➡')
btn22 = types.KeyboardButton('⬅ Назад')
page_1.row(btn1, btn2)
page_1.row(btn22)

page_2 = types.ReplyKeyboardMarkup(resize_keyboard=True)
btn1 = types.KeyboardButton('⬅Предыдущая страница')
btn22 = types.KeyboardButton('⬅ Назад')
page_2.row(btn1)
page_2.row(btn22)
